[build]
  command = "npm ci && npm run build"
  publish = ".next"
  functions = "functions"

[dev]
  command = "npm run dev"
  port = 3000

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200
